### ISSUE TITLE
Problem trying to change parameters

### ISSUE THREAD

**Issue by Jorge-hercas** [robjhyndman/MonashEBSTemplates#11]
Hi, and thanks for reading me

I am trying to enter my email in the corresponding field, but when rendering the document, the sample email is recompiled. Is it a bug?

The preamble is:

```
---
title: "Pronóstico de servicios"
author:
- familyname: Hernández Castelán
  othernames: Jorge Valente
  address: IKE Asistencia
  email: vhernandez@ikeasistencia.com
  correspondingauthor: true
  qualifications: Economista
department: Equipo de\newline Business Inteligence
organization: IKE Asistencia
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  MonashEBSTemplates::report:
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```
