### ISSUE TITLE
Problems with toc links

### ISSUE THREAD

**Issue by CarolineXGao** [robjhyndman/MonashEBSTemplates#8]
Hi Rob, 

When I was using the "monashwp.tex" with bookdown.  It seems that the following code has made hyperlinks of toc and pdf bookmarks to the wrong page: 

```
\usepackage[unicode=true]{hyperref}
$if(colorlinks)$
\PassOptionsToPackage{usenames,dvipsnames}{color} % color is loaded by hyperref
$endif$
\hypersetup{
$if(title-meta)$
            pdftitle={$title-meta$},
$endif$
$if(author-meta)$
            pdfauthor={$author-meta$},
$endif$
$if(keywords)$
            pdfkeywords={$for(keywords)$$keywords$$sep$, $endfor$},
$endif$
$if(colorlinks)$
            colorlinks=true,
            linkcolor=$if(linkcolor)$$linkcolor$$else$Maroon$endif$,
            citecolor=$if(citecolor)$$citecolor$$else$Blue$endif$,
            urlcolor=$if(urlcolor)$$urlcolor$$else$Blue$endif$,
$else$
            pdfborder={0 0 0},
$endif$
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
```

I have an example here: https://github.com/CarolineXGao/GSP/tree/main/Draft. The "template.tex" file is a simplified version  "monashwp.tex".  If the above code is added, then the links would be incorrect.  I am not sure if it is an issue with using bookdown. However, I couldn't figure out why it is the case. 

Thanks~~

Best,
Caroline

**Comment by robjhyndman** [comment]
Please provide a reproducible example of the problem.

**Comment by CarolineXGao** [comment]
Thanks Rob, 

Here is an Rmd file

`---
title: "Test"
author:
  familyname: Doe
  othernames: John
output:
   bookdown::pdf_document2:
     toc: yes
     number_sections: false
     latex_engine: xelatex
     pandoc_args:
      - --template=monashwp.tex
geometry: margin=1in
fontsize: 11pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy.opts = list(width.cutoff = 45), tidy = TRUE )
```

# Preface

\newpage 

# Chapter 1

\newpage 

# Chapter 2 

\newpage 

# Chapter 3 

\newpage 

# Chapter 4
`

Best, 

Caroline

**Comment by robjhyndman** [comment]
This doesn't use the package. Here is the template yaml when you use the package:

```
---
title: "Our great idea"
author:
- familyname: Curie
  othernames: Marie
  address: University of Paris
  email: mcurie.notreal@gmail.com
  correspondingauthor: true
  qualifications: Nobel Prize, PhD
- familyname: Curie
  othernames: Pierre
  address: University of Paris
  qualifications: Nobel Prize, PhD
abstract: "A brief summary of our ideas"
keywords: "blah, blah"
wpnumber: no/yr
jelcodes: C10,C14,C22
blind: false
cover: true
toc: false
bibliography: references.bib
biblio-style: authoryear-comp
output:
  MonashEBSTemplates::workingpaper:
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
---
```
